replicaCount: 1

image:
  repository: nodejs-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

containerPort: 3000

serviceAccount:
  create: false

ingress:
  enabled: false  # Change to true if you want to enable ingress
  className: "nginx"
  annotations: {}
  hosts:
    - host: nodejs.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false  # Change to true if you want HPA
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80